name    'xebia/nexus'
version '0.0.1'
source 'UNKNOWN'
author 'xebia'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'xebia/utils', '>= 0.0.1'
